ALTER TABLE alerts ADD COLUMN IF NOT EXISTS verdict TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS confidence FLOAT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS mitre_techniques TEXT[];
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS auto_execute BOOLEAN DEFAULT false;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS blast_radius TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS triaged_at TIMESTAMPTZ;
